<?php

namespace Lexing\WorkflowBundle\Repository;

/**
 * TaskLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskLogRepository extends \Doctrine\ORM\EntityRepository
{
}
