<?php

namespace Lexing\WorkflowBundle\Repository;

/**
 * TaskAssignmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskAssignmentRepository extends \Doctrine\ORM\EntityRepository
{
}
