<?php

namespace Lexing\WorkflowBundle\Repository;

/**
 * TaskEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskEntryRepository extends \Doctrine\ORM\EntityRepository
{
}
