<?php

namespace Lexing\LoanBundle\Repository;

/**
 * CreditExtensionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreditExtensionRepository extends \Doctrine\ORM\EntityRepository
{
}
