<?php

namespace Lexing\LoanBundle\Repository;

/**
 * CreditApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreditApplicationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * 返回creditApply、dealer、creditExtension
     *
     * @param array     $params
     *
     * @return mixed
     */
    public function getCredit($params){
        $dql = 'SELECT ca FROM LexingLoanBundle:CreditApplication ca LEFT JOIN ca.dealer d LEFT JOIN d.creditExtension e WHERE ca.dealer = :dealer';

        $credit = $this->getEntityManager()->createQuery($dql)
            ->setParameters($params)
            ->getOneOrNullResult();

        return $credit;
    }
}
