<?php

namespace Lexing\LoanBundle\Repository;

/**
 * LoanProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoanProductRepository extends \Doctrine\ORM\EntityRepository
{
}
