<?php

namespace Lexing\LoanBundle\Repository;

/**
 * VehicleMortgageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehicleMortgageRepository extends \Doctrine\ORM\EntityRepository
{
}
