<?php

namespace Lexing\VehicleBundle\Repository;

/**
 * VehicleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehicleRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * 传入dealer对象，返回车商旗下再售的车辆数量
     *
     * @param object    $dealer
     *
     * @return mixed
     */
    public function nbOnSale($dealer)
    {
        $dql = 'SELECT COUNT(v.id) FROM LexingVehicleBundle:Vehicle v WHERE v.dealer = :dealer AND v.onSale = :onSale';
        $nbOnSale = $this->getEntityManager()->createQuery($dql)
            ->setParameters(['dealer' => $dealer, 'onSale' => true])
            ->getSingleScalarResult();
        return $nbOnSale;
    }
}
