<?php

namespace Lexing\VehicleBundle\Repository;

/**
 * VehicleBrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehicleBrandRepository extends \Doctrine\ORM\EntityRepository
{
}
