<?php

namespace Lexing\VehicleBundle\Repository;

/**
 * VehicleSouRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehicleSouRepository extends \Doctrine\ORM\EntityRepository
{
}
