<?php

namespace Lexing\VehicleBundle\Repository;

/**
 * VehicleSerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehicleSerieRepository extends \Doctrine\ORM\EntityRepository
{
}
