<?php

namespace Lexing\VehicleBundle\Repository;

/**
 * VehicleModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehicleModelRepository extends \Doctrine\ORM\EntityRepository
{
}
