<?php

namespace Nnv\TaxonomyBundle\Repository;

/**
 * TaxonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxonRepository extends \Doctrine\ORM\EntityRepository
{
}
