<?php

namespace Lexing\DealerBundle\Repository;

/**
 * DealerAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DealerAccountRepository extends \Doctrine\ORM\EntityRepository
{
}
