<?php

namespace Lexing\DealerBundle\Repository;
use Carbon\Carbon;
use Lexing\VehicleBundle\Entity\Vehicle;
use Lexing\VehicleBundle\Entity\VehicleBrand;
use Lexing\VehicleBundle\Entity\VehicleModel;
use Lexing\VehicleBundle\Entity\VehicleSerie;

use Symfony\Component\Validator\Constraints\IsTrue;
use Symfony\Component\Validator\ConstraintViolation;
use Symfony\Component\Validator\Validation;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Type;

/**
 * VehicleDealerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehicleDealerRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $payload
     * @param VehicleModel $model
     * @return bool
     */
    public function storeVehicle(
        $payload,
        VehicleModel $model,
        $dealer = null
    )
    {
        $vehicleModel = new Vehicle();

        $vehicleModel->setColor($payload['color']);
        $vehicleModel->setVin($payload['vin']);
        $vehicleModel->setOnSale($payload['sale']);
        $vehicleModel->setPic($payload['image']);
        $vehicleModel->setMileage($payload['mileage']);
        $vehicleModel->setKind($payload['kind']);
        $vehicleModel->setDealer($dealer);
        $vehicleModel->setAssocModel($model);
        //$vehicleModel->getModel()->setYear(Carbon::parse($payload['register_date'])->year);

        $this->_em->persist($vehicleModel);
        $this->_em->flush();

        return true;
    }

    /**
     * @var array
     */
    public $result = [];

    /**
     * @param $payload
     * @return bool
     */
    public function validate($payload)
    {
        $validator = Validation::createValidator();
        $validatorList = [
            'brand_id' => [
                new NotBlank(),
            ],
            'color' => [
                new NotBlank(),
            ],
            'image' => [
                new NotBlank(),
            ],
            'mileage' => [
                new NotBlank(),
            ],
            'model_id' => [
                new NotBlank(),
            ],
            'register_date' => [
                new NotBlank(),
            ],
            'sale' => [
                new NotBlank(),
            ],
            'series_id' => [
                new NotBlank(),
            ],
            'vin' => [
                new Length(['max' => 50]),
                new NotBlank(),
            ],
            'kind' => [
                new NotBlank(),
            ],
        ];

        if (!in_array($payload['kind'], [Vehicle::BRANDNEW, Vehicle::SECONDHAND])) {
            throw new \RuntimeException('Payload\'s kind incorrect.');
        }

        foreach ($validatorList as $source => $item) {
            if (isset($payload[$source])) {
                $this->patternOf(
                    $payload[$source],
                    $item,
                    $validator
                );
            } else {
                throw new \RuntimeException('Payload\'s Index ' . $source . ' undefine.');
            }
        }

        return $this->result();
    }

    /**
     * @param $source
     * @param $validator
     * @param $valid
     */
    public function patternOf(
        $source, $item, $valid
    ) {
        $violations = $valid->validate($source, $item);

        if (0 !== count($violations)) {
            foreach ($violations as $violation) {
                /** @var ConstraintViolation $violation */
                if (!empty($source)) {
                    $this->result[] = [
                        'field'      => $source,
                        'parameters' => (array)$violation->getParameters(),
                        'message'    => $violation->getMessage()
                    ];
                }
            }

        } else {
            // $this->result = [];
        }
    }

    /**
     * null is right.
     *
     * @return bool|array
     */
    public function result()
    {
        if (is_array($this->result) AND $this->result != []) {
            return $this->result;
        }

        return null;
    }
}
