services:
#    lexing_user.example:
#        class: Lexing\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    lexing_user.admin.user:
        class: Lexing\UserBundle\Admin\UserAdmin
        arguments: [~, Lexing\UserBundle\Entity\User, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 用户, label: 用户 }
