<?php

namespace Lexing\SouCheBundle\Repository;

/**
 * SouBrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SouBrandRepository extends \Doctrine\ORM\EntityRepository
{
}
