<?php

namespace Lexing\SouCheBundle\Repository;

/**
 * SouModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SouModelRepository extends \Doctrine\ORM\EntityRepository
{
}
