<?php

namespace Lexing\SouCheBundle\Repository;

/**
 * SouSerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SouSerieRepository extends \Doctrine\ORM\EntityRepository
{
}
