<?php

namespace Lexing\TradeBundle\Repository;

/**
 * VehicleTradeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehicleTradeRepository extends \Doctrine\ORM\EntityRepository
{
}
