services:
#    lexing_imported_car.example:
#        class: Lexing\ImportedCarBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    lexing_imported_car.admin.imported_vehicle:
        class: Lexing\ImportedCarBundle\Admin\ImportedVehicleAdmin
        arguments: [~, Lexing\ImportedCarBundle\Entity\ImportedVehicle, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: 进口车辆管理}

    lexing_imported_car.admin.imported_brand:
        class: Lexing\ImportedCarBundle\Admin\ImportedBrandAdmin
        arguments: [~, Lexing\ImportedCarBundle\Entity\ImportedBrand, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: 品牌管理}

    lexing_imported_car.admin.imported_series:
        class: Lexing\ImportedCarBundle\Admin\ImportedSeriesAdmin
        arguments: [~, Lexing\ImportedCarBundle\Entity\ImportedSeries, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: 车系管理}

    lexing_imported_car.admin.imported_model:
        class: Lexing\ImportedCarBundle\Admin\ImportedModelAdmin
        arguments: [~, Lexing\ImportedCarBundle\Entity\ImportedModel, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: 车型管理}
