<?php

namespace Lexing\ImportedCarBundle\Repository;

/**
 * ImportedSeriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImportedSeriesRepository extends \Doctrine\ORM\EntityRepository
{
}
