<?php

namespace Lexing\ImportedCarBundle\Repository;

/**
 * ImportedBrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImportedBrandRepository extends \Doctrine\ORM\EntityRepository
{
}
