<?php

namespace Lexing\ImportedCarBundle\Repository;

/**
 * ImportedModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImportedModelRepository extends \Doctrine\ORM\EntityRepository
{
}
