<?php

namespace Lexing\MartBundle\Repository;

/**
 * VehicleMartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehicleMartRepository extends \Doctrine\ORM\EntityRepository
{
}
