<?php

namespace Lexing\DeviceBundle\Repository;

/**
 * DealerWPosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DealerWPosRepository extends \Doctrine\ORM\EntityRepository
{
}
